#pragma once

// Facing, as an integer that cannot drift.
//
// An angle here is a BAM — a binary angle, 65536 units to the full turn. Two
// properties earn it its place in simulation state:
//
//   * it WRAPS by construction. Turning right forever is `yaw += rate` on an
//     int32 with -fwrapv; there is no normalise step to forget and no `fmod`
//     that returns a different last bit on someone else's libm.
//   * 65536 units is 0.0055 degrees per step, which is finer than a mouse
//     reports and far finer than a frame shows.
//
// Direction vectors come from a QUARTER-TURN SINE TABLE OF LITERAL INTEGERS,
// interpolated in fixed point. Not std::sin, and not a table generated by a
// constexpr double loop either: both make the direction a body walks in a
// property of the host's floating-point library, and this project's whole
// determinism argument is that simulation state is not.
//
// COMPASS CONVENTION, fixed here and nowhere else:
//
//        yaw 0      = north, which is -Y (toward the harbour)
//        yaw 16384  = east,  which is +X
//        yaw 32768  = south, which is +Y
//        yaw 49152  = west,  which is -X
//
// so yaw increases CLOCKWISE looking down at the map, and
// forward = (sin yaw, -cos yaw), right = (cos yaw, sin yaw).

#include <cstdint>
#include <string_view>

#include "granadad/sim/fixed.hpp"

namespace granadad::sim {

/// A binary angle. 65536 units to the turn; wraps.
using Angle = std::int32_t;

inline constexpr Angle kTurnFull = 65536;
inline constexpr Angle kTurnHalf = kTurnFull / 2;
inline constexpr Angle kTurnQuarter = kTurnFull / 4;

inline constexpr Angle kFacingNorth = 0;
inline constexpr Angle kFacingEast = kTurnQuarter;
inline constexpr Angle kFacingSouth = kTurnHalf;
inline constexpr Angle kFacingWest = 3 * kTurnQuarter;

/// Degrees to BAM, rounded. Compile-time convenience for authoring constants;
/// never on a hot path and never fed from state.
[[nodiscard]] constexpr Angle angle_from_degrees(std::int32_t degrees) noexcept {
    return static_cast<Angle>((static_cast<std::int64_t>(degrees) * kTurnFull + 180) / 360);
}

/// Sine and cosine are Q16: 65536 is 1.0.
inline constexpr std::int32_t kTrigOne = 65536;

namespace detail {

/// sin(i * pi/2 / 256) * 65536, rounded to nearest, for i in [0, 256].
///
/// Literal integers on purpose. See the header comment: a table built by a
/// constexpr loop over doubles would be a different table on a compiler whose
/// long double is 80-bit, and the difference would surface as a body walking a
/// hair off course on one machine and hashing differently on another.
inline constexpr std::int32_t kQuarterSine[257] = {
        0,   402,   804,  1206,  1608,  2010,  2412,  2814,
     3216,  3617,  4019,  4420,  4821,  5222,  5623,  6023,
     6424,  6824,  7224,  7623,  8022,  8421,  8820,  9218,
     9616, 10014, 10411, 10808, 11204, 11600, 11996, 12391,
    12785, 13179, 13573, 13966, 14359, 14751, 15142, 15533,
    15923, 16313, 16702, 17091, 17479, 17866, 18253, 18639,
    19024, 19409, 19792, 20175, 20557, 20939, 21320, 21699,
    22078, 22456, 22834, 23210, 23586, 23960, 24334, 24707,
    25079, 25450, 25820, 26189, 26557, 26925, 27291, 27656,
    28020, 28383, 28745, 29106, 29466, 29824, 30182, 30538,
    30893, 31248, 31600, 31952, 32303, 32652, 33000, 33347,
    33692, 34037, 34380, 34721, 35062, 35401, 35738, 36075,
    36410, 36744, 37076, 37407, 37736, 38064, 38391, 38716,
    39040, 39362, 39683, 40002, 40320, 40636, 40951, 41264,
    41576, 41886, 42194, 42501, 42806, 43110, 43412, 43713,
    44011, 44308, 44604, 44898, 45190, 45480, 45769, 46056,
    46341, 46624, 46906, 47186, 47464, 47741, 48015, 48288,
    48559, 48828, 49095, 49361, 49624, 49886, 50146, 50404,
    50660, 50914, 51166, 51417, 51665, 51911, 52156, 52398,
    52639, 52878, 53114, 53349, 53581, 53812, 54040, 54267,
    54491, 54714, 54934, 55152, 55368, 55582, 55794, 56004,
    56212, 56418, 56621, 56823, 57022, 57219, 57414, 57607,
    57798, 57986, 58172, 58356, 58538, 58718, 58896, 59071,
    59244, 59415, 59583, 59750, 59914, 60075, 60235, 60392,
    60547, 60700, 60851, 60999, 61145, 61288, 61429, 61568,
    61705, 61839, 61971, 62100, 62228, 62353, 62475, 62596,
    62714, 62829, 62942, 63053, 63162, 63268, 63372, 63473,
    63572, 63668, 63763, 63854, 63944, 64031, 64115, 64197,
    64277, 64354, 64429, 64501, 64571, 64639, 64704, 64766,
    64827, 64884, 64940, 64993, 65043, 65091, 65137, 65180,
    65220, 65259, 65294, 65328, 65358, 65387, 65413, 65436,
    65457, 65476, 65492, 65505, 65516, 65525, 65531, 65535,
    65536,
};

/// The full-turn sine at one of 1024 steps, extended to accept step 1024 so the
/// interpolator can always read `t` and `t+1`.
[[nodiscard]] constexpr std::int32_t stepSine(std::int32_t t) noexcept {
    if (t <= 256) {
        return kQuarterSine[t];
    }
    if (t <= 512) {
        return kQuarterSine[512 - t];
    }
    if (t <= 768) {
        return -kQuarterSine[t - 512];
    }
    return -kQuarterSine[1024 - t];
}

}  // namespace detail

/// sin(angle) in Q16. Table lookup at 1024 steps plus a linear blend over the
/// low 6 bits, so the answer tracks the full 65536-step angle to about a part
/// in 20000 — and does it with nothing but int arithmetic.
[[nodiscard]] constexpr std::int32_t sin_q16(Angle angle) noexcept {
    const std::int32_t wrapped = angle & (kTurnFull - 1);
    const std::int32_t step = wrapped >> 6;
    const std::int32_t frac = wrapped & 63;
    const std::int32_t a = detail::stepSine(step);
    if (frac == 0) {
        return a;
    }
    const std::int32_t b = detail::stepSine(step + 1);
    return wrap_add(a, static_cast<std::int32_t>((static_cast<std::int64_t>(b - a) * frac) >> 6));
}

[[nodiscard]] constexpr std::int32_t cos_q16(Angle angle) noexcept {
    return sin_q16(wrap_add(angle, kTurnQuarter));
}

/// Forward, on the map plane, for a facing. North is -Y.
[[nodiscard]] constexpr std::int32_t forward_x_q16(Angle yaw) noexcept {
    return sin_q16(yaw);
}
[[nodiscard]] constexpr std::int32_t forward_y_q16(Angle yaw) noexcept {
    return wrap_neg(cos_q16(yaw));
}
/// Strafe-right for a facing.
[[nodiscard]] constexpr std::int32_t right_x_q16(Angle yaw) noexcept {
    return cos_q16(yaw);
}
[[nodiscard]] constexpr std::int32_t right_y_q16(Angle yaw) noexcept {
    return sin_q16(yaw);
}

/// The eight-point compass letter for a facing — what the HUD needle names.
/// Rounds to the nearest of N, NE, E, SE, S, SW, W, NW.
[[nodiscard]] std::string_view compass_point(Angle yaw) noexcept;

}  // namespace granadad::sim
